# Generated by Django 2.2.17 on 2020-11-17 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('rid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceImages',
            fields=[
                ('rid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('puid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImages',
            fields=[
                ('rid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('puid', models.UUIDField()),
            ],
        ),
    ]
