# Generated by Django 2.2.17 on 2020-11-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_emotionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimages',
            name='image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
