# Generated by Django 2.2.17 on 2020-12-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_uploadedimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='uploadedimages',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
